# filebeat.config:
# modules:
# path: ${path.config}/modules.d/*.yml
# reload.enabled: false

# setup.kibana:
#   host: "172.19.0.6:5601"

# processors:
#   - add_cloud_metadata: ~
processors:
- drop_fields:
    fields: ["host"] # ELS v6.x+ 会引起index mapping问题,所以将其忽略

filebeat.inputs: #多个输入流以`-`的方式声明
- type: tcp
  max_message_size: 10MiB
  host: "0.0.0.0:13012"
    # fields:
    # nagios_host:
  # nagios_service:

output.logstash:
  hosts: ["172.19.0.7:5044"]
  bulk_max_size: 409600
  enabled: true
  # nagios_host:
  # nagios_service:
  #username: '${ELASTICSEARCH_USERNAME:}'
  #password: '${ELASTICSEARCH_PASSWORD:}'
