filebeat.processors:
#- type: tcp
#  enabled: true
#  max_message_size: 10MiB
#  host: "0.0.0.0:13012"
#  tags: ["hig-elk"]
- type: log
  enabled: true
  paths:
    - /usr/src/app/elklog.log
  fields:
    type: hig_elk
  fields_under_root: true
  json.keys_under_root: true
#filebeat.inputs: #多个输入流以`-`的方式声明
#- type: tcp
#  max_message_size: 10MiB
#  host: "0.0.0.0:13012"
#- type: file
#  paths:
#  - /usr/src/app
    # fields:
    # nagios_host:
  # nagios_service:

output.logstash:
  enabled: true
  compression_level: 1
  hosts: ["10.0.0.12:5044","10.0.1.133:5044"]
  loadbalance: true
  bulk_max_size: 2048
