processors:
- drop_fields:
    fields: ["host"]
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/src/app/*.log
  fields:
    type: hig_elk
  fields_under_root: true
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  ignore_older: 48h
  clean_inactive: 72h

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.kibana:
output.logstash:
  enabled: true
  compression_level: 1
  hosts: ["10.0.0.12:5044","10.0.1.133:5044"]
  loadbalance: true
  bulk_max_size: 2048
logging.level: info
logging.json: true
