processors:
- drop_fields:
    fields: ["host","log.file.path","log.offset"]
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/src/app/elklog.log
  fields:
    type: hig_elk
  fields_under_root: true
  json.keys_under_root: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
filebeat.spool_size: 4096
filebeat.idle_timeout: 2s
setup.kibana:
output.logstash:
  enabled: true
  compression_level: 1
  hosts: ["10.0.0.12:5044","10.0.1.133:5044"]
  loadbalance: true
  bulk_max_size: 2048
logging.level: error
