#filebeat.processors:
#- type: tcp
#  enabled: true
#  max_message_size: 10MiB
#  host: "0.0.0.0:13012"
#  tags: ["hig-elk"]
#- type: log
#  enabled: true
#  paths:
#    - /usr/src/app/elklog.log
#  fields:
#    type: hig_elk
#  fields_under_root: true
#  json.keys_under_root: true

filebeat.inputs: #多个输入流以`-`的方式声明
- type: tcp
  enabled: true
  max_message_size: 10MiB
  host: "0.0.0.0:13012"

#- type: file
#  paths:
#  - /usr/src/app
    # fields:
    # nagios_host:
  # nagios_service:

filebeat.config.modules:
  path: /filebeat-7.0.0-linux-x86_64/modules.d/*.yml
  reload.enabled: false
#setup.template.settings:
#  index.number_of_shards: 3
#filebeat.spool_size: 4096
#filebeat.idle_timeout: 2s

output.logstash:
  enabled: true
  compression_level: 1
  hosts: ["10.0.0.12:5044","10.0.1.133:5044"]
  loadbalance: true
  bulk_max_size: 2048

#logging.to_files: true
#logging.files:
#  path: /var/log/filebeat
#  name: filebeat
#  keepfiles: 10
#  permissions: 0600
